import json
import re

HOSPITAL_BOILERPLATE_DEPT = """
At Sarvada Hospito Care, patient safety and clinical excellence form the core of our surgical philosophy. We adhere to stringent international protocols for infection control, ensuring that our operating theaters maintain the highest standards of sterility. Our surgical suites are equipped with state-of-the-art life support systems, advanced anesthesia workstations, and high-definition monitoring equipment, allowing our surgeons to operate with unparalleled precision and confidence. Beyond the technology, our multidisciplinary team of experienced surgeons, dedicated anesthesiologists, and specialized perioperative nurses work collaboratively to deliver comprehensive, compassionate care tailored to the unique physiological and psychological needs of each patient.

From the moment a patient is admitted for surgery, our dedicated care coordinators ensure a seamless and stress-free experience. We conduct thorough pre-anesthetic checkups, detailed counseling sessions, and comprehensive risk assessments to mitigate any potential intraoperative or postoperative complications. We believe in empowering our patients through transparent communication, providing them with clear, accessible information regarding their diagnosis, the proposed surgical intervention, potential alternatives, and the expected recovery trajectory. This patient-centric approach not only alleviates anxiety but also fosters a strong therapeutic alliance between the patient and the healthcare team, which is crucial for optimal healing.

Postoperative care is a critical component of the surgical journey at Sarvada Hospito Care. Our dedicated Post-Anesthesia Care Unit (PACU) and Intensive Care Units (ICU) are staffed round-the-clock by specialized intensivists and critical care nurses. We utilize advanced multimodal pain management protocols, focusing on minimizing discomfort and facilitating early mobilization, which is essential for preventing complications such as deep vein thrombosis and pulmonary infections. Our physiotherapy and rehabilitation teams are integrated into the recovery process from day one, developing personalized rehabilitation programs that accelerate healing and restore functional independence.

Furthermore, our hospital's commitment to continuous quality improvement is reflected in our rigorous clinical audits and ongoing medical education programs. Our surgeons regularly participate in national and international conferences, ensuring that they remain at the forefront of surgical innovation. By integrating evidence-based practices, advanced surgical technologies, and a profound commitment to compassionate care, Sarvada Hospito Care stands as a beacon of excellence in the region, dedicated to improving the health and well-being of our community through superior surgical outcomes. We ensure that every patient receives the highest level of care, support, and medical expertise available, prioritizing their long-term health and successful recovery above all else.
"""

HOSPITAL_BOILERPLATE_TREATMENT = """
Choosing the right healthcare facility for this specific surgical procedure is a decision that significantly impacts the overall clinical outcome and the patient's quality of life. At Sarvada Hospito Care, we recognize the profound trust placed in us by our patients and their families. This procedure is performed in our ultra-modern, fully equipped surgical suites, which feature advanced airflow systems designed to minimize the risk of intraoperative infections. Our surgical teams utilize the latest generation of surgical instruments, high-definition imaging systems, and precision technologies, enabling highly targeted interventions that preserve surrounding healthy tissues and optimize functional recovery.

The comprehensive care pathway for this treatment begins with an exhaustive pre-operative diagnostic workup. Our state-of-the-art diagnostic imaging center provides our surgical team with high-resolution, three-dimensional anatomical maps, allowing for meticulous pre-surgical planning. This detailed preparation is essential for anticipating potential anatomical variations and ensuring the highest degree of surgical precision. Our specialized pre-admission counseling team works closely with each patient, addressing all concerns, explaining the procedural steps in accessible language, and outlining the expected postoperative timeline, thereby ensuring that patients are mentally and physically prepared for the intervention.

Recovery and rehabilitation following this treatment are managed with the utmost diligence and personalized attention. Our multimodal approach to pain management ensures that patients remain comfortable throughout their hospital stay, facilitating early ambulation and participation in physiotherapy. Our expert physiotherapists design customized rehabilitation protocols aimed at restoring mobility, strength, and overall functional capacity. We also provide comprehensive nutritional counseling, as optimal nutrition is a vital component of the tissue healing and recovery process. Our dedicated nursing staff provides continuous monitoring and compassionate support, addressing any immediate postoperative needs with expertise and empathy.

Upon discharge, our commitment to our patients continues through a structured follow-up program. We provide detailed discharge summaries, clear instructions regarding wound care, medication management, and activity modifications. Our clinical coordinators schedule regular follow-up appointments to monitor healing progress, assess functional recovery, and address any late-onset complications. Our multidisciplinary approach ensures that all aspects of the patient's recovery are carefully managed, from surgical healing to functional rehabilitation. By choosing Sarvada Hospito Care, patients are assured of receiving not just a surgical procedure, but a comprehensive, compassionate, and highly professional continuum of care designed to achieve the best possible long-term health outcomes.
"""

depts_data = [
  {
    "name": "General Surgery",
    "slug": "general-surgery",
    "icon": "✂️",
    "category": "Surgical Services",
    "available": "24/7",
    "description": "Comprehensive general surgical procedures including appendectomy, hernia repair, and GI surgeries.",
    "intro": "The General Surgery department at Sarvada Hospito Care is a cornerstone of our medical facility, providing a vast array of essential surgical interventions. Our highly skilled general surgeons possess extensive expertise in managing both routine and complex surgical conditions affecting the abdomen, digestive tract, endocrine system, and soft tissues. We prioritize minimally invasive techniques whenever clinically appropriate, ensuring reduced postoperative pain, minimal scarring, and an accelerated return to normal daily activities. Our department is fully equipped to handle emergency surgical cases round-the-clock, providing life-saving interventions for conditions such as acute appendicitis, perforated ulcers, intestinal obstructions, and severe abdominal trauma.",
    "features": ["Hernia Repair", "Appendectomy", "GI Surgery", "Piles & Fistula"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 9,
    "treatments": [
      {"name": "Piles / Haemorrhoids (Stapler Haemorrhoidectomy PPH)", "slug": "piles-haemorrhoids-stapler-haemorrhoidectomy", "desc": "Stapler Haemorrhoidectomy, also known as Procedure for Prolapse and Hemorrhoids (PPH), is an advanced, minimally invasive surgical technique for treating internal hemorrhoids. Unlike traditional open surgery, this procedure utilizes a specialized circular stapling device to remove a circumferential ring of excess hemorrhoidal tissue high within the anal canal, where there are fewer pain receptors. This significantly reduces postoperative pain and discomfort, allowing for a much faster recovery and a quicker return to normal activities while effectively restoring the normal anatomical position of the hemorrhoidal cushions."},
      {"name": "Piles Laser Surgery", "slug": "piles-laser-surgery", "desc": "Laser Surgery for Piles (Laser Hemorrhoidoplasty) is a cutting-edge, minimally invasive treatment that uses focused laser energy to shrink and ablate hemorrhoidal tissue. The laser beam coagulates the blood vessels supplying the hemorrhoid, causing it to shrink without the need for extensive surgical excision. This precise technique minimizes damage to the surrounding healthy tissues, resulting in significantly less postoperative pain, reduced bleeding, and a remarkably fast recovery period. It is performed as a day-care procedure, allowing patients to go home the same day."},
      {"name": "Anal Fissure Repair (Sphincterotomy)", "slug": "anal-fissure-repair", "desc": "Lateral Internal Sphincterotomy is the gold-standard surgical treatment for chronic anal fissures that have not responded to conservative medical management. The procedure involves making a small, precise incision in the internal anal sphincter muscle to relieve the underlying muscle spasm and reduce resting pressure. This immediate reduction in pressure significantly improves blood flow to the area, facilitating the rapid healing of the fissure and providing profound, immediate relief from the severe pain and discomfort associated with bowel movements."},
      {"name": "Fistula-in-Ano Surgery (Fistulotomy / LIFT / Flap)", "slug": "fistula-in-ano-surgery", "desc": "Fistula-in-Ano Surgery encompasses a range of techniques tailored to the complexity and location of the fistula tract. Procedures range from a simple fistulotomy, where the tract is laid open to heal from the inside out, to advanced sphincter-saving procedures like the Ligation of Intersphincteric Fistula Tract (LIFT) or mucosal advancement flaps. Our experienced colorectal surgeons carefully evaluate each case using advanced imaging modalities to determine the most appropriate surgical approach, aiming to completely eradicate the infection while meticulously preserving fecal continence and anal sphincter function."},
      {"name": "Laparoscopic Appendectomy", "slug": "laparoscopic-appendectomy-general", "desc": "Laparoscopic Appendectomy is the modern, minimally invasive approach for the surgical removal of an inflamed or infected appendix (appendicitis). Utilizing specialized surgical instruments and a high-definition laparoscope inserted through several tiny incisions in the abdomen, the surgeon precisely visualizes and extracts the appendix. This technique offers significant advantages over traditional open surgery, including drastically reduced postoperative pain, a lower risk of surgical site infections, virtually invisible scarring, and a much faster overall recovery, enabling patients to quickly resume their normal lives."}
    ]
  },
  {
    "name": "Orthopedic Surgery",
    "slug": "orthopedic-surgery",
    "icon": "🦴",
    "category": "Surgical Services",
    "available": "24/7",
    "description": "Advanced bone and joint care including joint replacements and trauma surgery.",
    "intro": "The Orthopedic Surgery department at Sarvada Hospito Care is dedicated to providing comprehensive, world-class care for a wide spectrum of musculoskeletal disorders. Our highly specialized team of orthopedic surgeons, sports medicine specialists, and dedicated physical therapists work collaboratively to diagnose and treat conditions affecting the bones, joints, ligaments, tendons, and muscles. We offer advanced surgical interventions ranging from complex joint arthroplasty (replacements) and advanced arthroscopic (keyhole) sports surgeries to intricate fracture fixation and pediatric orthopedics. Our goal is to restore mobility, alleviate pain, and significantly enhance the overall quality of life for our patients.",
    "features": ["Joint Replacement", "Fracture Care", "Sports Injuries", "Arthroscopy"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 10,
    "treatments": [
      {"name": "Total Knee Replacement (TKR)", "slug": "total-knee-replacement", "desc": "Total Knee Replacement (Arthroplasty) is a transformative surgical procedure designed to relieve severe pain and restore function in knee joints extensively damaged by advanced osteoarthritis, rheumatoid arthritis, or post-traumatic arthritis. The procedure involves meticulously removing the damaged cartilage and underlying bone from the distal femur and proximal tibia, and replacing them with high-quality, durable artificial implants made of specialized metal alloys and advanced biocompatible plastics. This surgery significantly improves joint mobility, corrects deformities, and dramatically enhances the patient's quality of life and independence."},
      {"name": "Total Hip Replacement (THR)", "slug": "total-hip-replacement", "desc": "Total Hip Replacement is a highly successful surgical intervention for individuals suffering from debilitating hip pain due to severe arthritis, avascular necrosis, or complex hip fractures. The procedure involves the precise surgical removal of the damaged femoral head and the worn acetabular socket, which are then replaced with a sophisticated prosthetic hip joint comprising a stem, a ball, and a socket. Utilizing advanced surgical techniques and materials, this procedure restores normal joint mechanics, significantly alleviates chronic pain, and allows patients to return to a high level of physical activity."},
      {"name": "ACL Reconstruction Surgery", "slug": "acl-reconstruction", "desc": "Anterior Cruciate Ligament (ACL) Reconstruction is a specialized, minimally invasive arthroscopic procedure performed to repair a torn ACL, a crucial stabilizing ligament in the knee joint frequently injured during high-impact sports. The surgery involves removing the damaged ligament remnants and meticulously replacing them with a biological tissue graft, typically harvested from the patient's own patellar or hamstring tendons. This precise reconstruction restores the structural integrity and rotational stability of the knee, enabling athletes and active individuals to confidently return to their demanding physical activities and competitive sports."},
      {"name": "Arthroscopic Meniscus Repair", "slug": "arthroscopic-meniscus-repair", "desc": "Arthroscopic Meniscus Repair is a highly targeted, minimally invasive surgical procedure utilized to address tears in the meniscus, the vital C-shaped cartilage discs that act as shock absorbers within the knee joint. Using a small arthroscope and specialized instruments inserted through tiny portal incisions, the surgeon visualizes the tear and precisely sutures the damaged tissue back together, preserving as much native cartilage as possible. This approach is critical for preventing early-onset osteoarthritis and maintaining long-term joint health, offering a faster recovery and less postoperative discomfort than traditional open surgery."},
      {"name": "Complex Fracture Fixation (Trauma Surgery)", "slug": "complex-fracture-fixation", "desc": "Complex Fracture Fixation involves the surgical stabilization and precise anatomical realignment of severe, multi-fragmentary, or open bone fractures resulting from high-energy trauma, such as road traffic accidents or falls from height. Our expert orthopedic trauma surgeons utilize a wide array of advanced internal fixation devices, including specialized titanium plates, intramedullary nails, and complex screw systems, as well as external fixators when necessary. This meticulous surgical intervention ensures proper bone healing, restores structural integrity, prevents devastating long-term deformities, and maximizes functional recovery for the patient."}
    ]
  },
  {
    "name": "Neurosurgery",
    "slug": "neurosurgery",
    "icon": "🧠",
    "category": "Surgical Services",
    "available": "24/7",
    "description": "Expert surgical care for brain, spine, and nervous system disorders.",
    "intro": "The Neurosurgery department at Sarvada Hospito Care represents the pinnacle of complex surgical intervention, dedicated to the precise diagnosis and meticulous treatment of intricate disorders affecting the brain, spinal cord, and peripheral nervous system. Our elite team of neurosurgeons utilizes the most advanced microsurgical techniques, state-of-the-art neuro-navigation systems, high-powered surgical microscopes, and intraoperative neuro-monitoring to perform highly complex procedures with uncompromising safety and precision. From life-saving interventions for severe traumatic brain injuries to the delicate resection of deep-seated brain tumors and complex spinal cord surgeries, our department is equipped to handle the most challenging neurological conditions.",
    "features": ["Neuro-Trauma", "Brain Tumors", "Spine Surgery", "Micro-neurosurgery"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 11,
    "treatments": [
      {"name": "Brain Tumor Excision", "slug": "brain-tumor-excision", "desc": "Brain Tumor Excision (Craniotomy for Tumor) is a highly complex and delicate neurosurgical procedure aimed at achieving the maximum safe resection of benign or malignant tumors located within the cranial cavity. Our expert neurosurgeons employ advanced preoperative neuroimaging, functional MRI mapping, and intraoperative neuro-navigation technologies to precisely localize the tumor and delineate its relationship with critical brain structures. Using state-of-the-art surgical microscopes and ultrasonic aspirators, the tumor is meticulously removed while preserving adjacent healthy brain tissue and vital neurological functions, minimizing the risk of postoperative deficits."},
      {"name": "Spinal Laminectomy (Decompression Surgery)", "slug": "spinal-laminectomy", "desc": "Spinal Laminectomy is a highly effective surgical procedure designed to alleviate debilitating pressure on the spinal cord or exiting spinal nerve roots caused by severe spinal stenosis, herniated discs, or bone spurs. The surgery involves the meticulous removal of the lamina—the posterior bony arch of the vertebra—thereby significantly enlarging the spinal canal and creating ample space for the neural structures. This critical decompression relieves severe radiating pain, numbness, and profound weakness in the extremities, dramatically improving the patient's mobility, neurological function, and overall quality of life."},
      {"name": "Endoscopic Pituitary Surgery", "slug": "endoscopic-pituitary-surgery", "desc": "Endoscopic Transsphenoidal Pituitary Surgery is an advanced, minimally invasive neurosurgical technique utilized for the highly precise removal of tumors located in the pituitary gland at the base of the brain. Instead of a traditional open craniotomy, the surgeon accesses the tumor through the natural nasal pathways using a specialized high-definition endoscope. This innovative approach provides superior visualization of the tumor and surrounding critical structures, such as the optic nerves, while completely avoiding external facial incisions, significantly reducing postoperative pain, shortening hospital stays, and accelerating patient recovery."},
      {"name": "Microdiscectomy (Spine)", "slug": "microdiscectomy", "desc": "Microdiscectomy is the gold-standard, minimally invasive surgical procedure for treating severe, medically refractory pain caused by a herniated lumbar disc pressing upon a spinal nerve root (sciatica). Using a specialized high-powered operating microscope and meticulously designed micro-instruments, the surgeon creates a very small incision to precisely remove only the herniated portion of the disc material that is compressing the nerve. This targeted approach preserves the overall structural integrity of the spine, resulting in immediate, profound relief from radiating leg pain and facilitating a remarkably rapid recovery and return to daily activities."},
      {"name": "Traumatic Brain Injury Management (Craniotomy for Hematoma)", "slug": "traumatic-brain-injury-craniotomy", "desc": "The surgical management of severe Traumatic Brain Injury (TBI) often requires an emergency decompressive craniotomy to evacuate life-threatening intracranial hematomas (blood clots) and dramatically relieve dangerously elevated intracranial pressure. This rapid, life-saving intervention involves temporarily removing a section of the skull to access the brain, carefully evacuating the accumulated blood, controlling active bleeding, and providing critical space for the swollen brain to expand safely. Our dedicated neuro-trauma team is available 24/7 to perform these critical procedures, significantly reducing mortality and optimizing the potential for neurological recovery."}
    ]
  },
  {
    "name": "Plastic Surgery",
    "slug": "plastic-surgery",
    "icon": "✨",
    "category": "Surgical Services",
    "available": "By Appointment",
    "description": "Reconstructive and aesthetic plastic surgery procedures.",
    "intro": "The Plastic Surgery department at Sarvada Hospito Care provides a comprehensive spectrum of reconstructive and aesthetic surgical procedures, dedicated to restoring form, function, and profound self-confidence. Our highly skilled, board-certified plastic surgeons combine deep medical expertise with refined artistic sensibility to achieve exceptionally natural-looking, harmonious, and functionally superior results. Whether reconstructing complex defects following severe trauma or oncological resections, performing intricate microsurgical tissue transfers, or providing state-of-the-art cosmetic enhancements, our department utilizes the most advanced surgical techniques and specialized materials to deliver personalized, transformative care.",
    "features": ["Burn Reconstruction", "Trauma Repair", "Aesthetic Surgery", "Scar Revision"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 12,
    "treatments": [
      {"name": "Burn Reconstruction Surgery", "slug": "burn-reconstruction", "desc": "Burn Reconstruction Surgery encompasses a complex series of specialized procedures designed to significantly improve the function and aesthetic appearance of burn scars and debilitating contractures. Our reconstructive experts utilize advanced techniques such as split-thickness and full-thickness skin grafting, local and regional tissue flaps, and sophisticated tissue expansion to replace severely damaged skin and meticulously release tight, restrictive scar tissue. This comprehensive, multi-staged approach aims to dramatically restore joint mobility, improve skin texture and elasticity, and alleviate the significant physical and profound psychological burdens associated with severe burn injuries."},
      {"name": "Cleft Lip and Palate Repair", "slug": "cleft-lip-palate-repair", "desc": "Cleft Lip and Palate Repair is a highly specialized, transformative reconstructive surgery performed on infants and young children to correct complex congenital facial deformities. The meticulous surgical repair focuses on seamlessly closing the separation in the lip and meticulously reconstructing the structural integrity of the roof of the mouth (palate). This critical intervention not only vastly improves the child's facial aesthetics but is also absolutely essential for restoring normal essential functions, including feeding, proper speech development, and optimal hearing, profoundly impacting the child's long-term development and quality of life."},
      {"name": "Complex Scar Revision", "slug": "complex-scar-revision", "desc": "Complex Scar Revision surgery aims to significantly minimize the clinical appearance of prominent, disfiguring, or functionally restrictive scars resulting from severe trauma, previous surgeries, or extensive burns. Our plastic surgeons employ a variety of refined surgical techniques, including precise geometric broken line closure, sophisticated Z-plasty, W-plasty, and specialized skin grafting or flap procedures, to carefully blend the scar with the surrounding natural skin tension lines. This meticulous approach significantly improves the cosmetic appearance, dramatically increases tissue flexibility, and relieves functional restrictions caused by hypertrophic or tight scar tissue."},
      {"name": "Breast Reconstruction (Post-Mastectomy)", "slug": "breast-reconstruction", "desc": "Breast Reconstruction is a deeply restorative surgical procedure designed to meticulously rebuild the shape, size, and natural appearance of the breast following a mastectomy or lumpectomy for breast cancer. Our specialized reconstructive surgeons offer comprehensive, personalized options, utilizing advanced silicone or saline implants, sophisticated autologous tissue flap techniques (using the patient's own tissue from the abdomen or back), or a combination of both. This complex, highly personalized surgery plays a profoundly vital role in restoring a woman's body image, emotional well-being, and overall psychological recovery following cancer treatment."},
      {"name": "Microsurgical Tissue Transfer (Free Flap)", "slug": "microsurgical-tissue-transfer", "desc": "Microsurgical Tissue Transfer, or Free Flap surgery, is an incredibly advanced, highly complex reconstructive technique used to repair massive, debilitating tissue defects resulting from severe trauma, extensive cancer resection, or major infections. The procedure involves the meticulous surgical harvesting of a complex block of tissue—including skin, fat, muscle, and occasionally bone—along with its dedicated blood supply from a healthy donor site on the patient's body. Utilizing high-powered surgical microscopes, these tiny blood vessels are painstakingly reconnected to blood vessels at the recipient site, ensuring the vital survival and complete integration of the transferred tissue."}
    ]
  },
  {
    "name": "Spinal Surgery",
    "slug": "spinal-surgery",
    "icon": "🦴",
    "category": "Surgical Services",
    "available": "24/7",
    "description": "Specialized surgical management of spinal disorders, disc prolapse, and spinal trauma.",
    "intro": "The Spinal Surgery department at Sarvada Hospito Care is a highly specialized, dedicated center of excellence focused exclusively on the comprehensive diagnosis and advanced surgical management of complex spinal disorders. Our multidisciplinary team of elite spine surgeons, neurologists, and specialized rehabilitation therapists employs a holistic, patient-centric approach to treat conditions affecting the cervical, thoracic, and lumbar spine. We are pioneers in utilizing advanced minimally invasive spine surgery (MISS) techniques, sophisticated intraoperative neuro-navigation, and state-of-the-art robotic assistance to significantly minimize tissue damage, reduce postoperative pain, and dramatically accelerate the recovery process.",
    "features": ["Disc Herniation", "Spinal Fusion", "Minimally Invasive Spine Surgery", "Spinal Trauma"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 13,
    "treatments": [
      {"name": "Minimally Invasive Spinal Fusion (MIS Fusion)", "slug": "minimally-invasive-spinal-fusion", "desc": "Minimally Invasive Spinal Fusion is a highly advanced surgical technique designed to permanently connect two or more unstable vertebrae, eliminating painful motion between them. Unlike traditional open fusion, this sophisticated procedure utilizes specialized tubular retractors inserted through very small incisions to carefully access the spine with minimal disruption to the surrounding delicate back muscles. Bone graft material and advanced spinal instrumentation (such as titanium screws and rods) are precisely placed to facilitate a solid, permanent bony fusion. This technique significantly reduces surgical blood loss, profoundly minimizes postoperative muscle pain, and allows for a remarkably faster recovery and earlier hospital discharge."},
      {"name": "Cervical Disc Replacement", "slug": "cervical-disc-replacement", "desc": "Artificial Cervical Disc Replacement is an innovative, motion-preserving surgical alternative to traditional spinal fusion for patients suffering from severe symptomatic cervical disc herniation or advanced degenerative disc disease in the neck. The procedure involves the meticulous removal of the damaged, compressive cervical disc and its replacement with a highly sophisticated artificial implant designed to closely mimic the complex, natural biomechanics of a healthy intervertebral disc. This advanced approach excellently relieves severe nerve compression, resolves debilitating arm pain, and crucially preserves the natural range of motion and flexibility in the neck, reducing significant stress on adjacent spinal levels."},
      {"name": "Endoscopic Discectomy", "slug": "endoscopic-discectomy", "desc": "Endoscopic Discectomy is an ultra-minimally invasive, cutting-edge surgical procedure used to precisely remove herniated disc material that is severely compressing a spinal nerve and causing intense radiating pain (sciatica). The surgeon utilizes a specialized, high-definition endoscope and microscopic instruments inserted through a tiny, keyhole incision (typically less than a centimeter). The endoscope provides exceptional, magnified visualization of the compressed nerve and the offending disc fragment, allowing for highly targeted and safe removal without the need to cut significant bone or muscle. This results in incredibly rapid recovery and immediate, profound pain relief."},
      {"name": "Scoliosis Correction Surgery", "slug": "scoliosis-correction-surgery", "desc": "Scoliosis Correction Surgery is a highly complex, major reconstructive procedure aimed at significantly straightening the spine and securely stabilizing the correction in patients suffering from severe, progressive spinal deformities. The intricate surgery involves meticulously attaching a complex system of specialized titanium rods, hooks, and pedicle screws to the significantly curved vertebrae, carefully realigning the spine to a more normal, balanced position. Bone grafts are then strategically placed to encourage permanent spinal fusion along the corrected segments. This critical procedure profoundly improves posture, prevents dangerous cardiopulmonary complications, and significantly enhances the patient's long-term quality of life."},
      {"name": "Kyphoplasty / Vertebroplasty", "slug": "kyphoplasty-vertebroplasty", "desc": "Kyphoplasty and Vertebroplasty are highly effective, minimally invasive, image-guided procedures specifically designed to treat excruciatingly painful vertebral compression fractures, most commonly caused by severe osteoporosis. Under continuous fluoroscopic guidance, a specialized needle is precisely inserted into the fractured, collapsed vertebra. In Kyphoplasty, a small orthopedic balloon is carefully inflated to restore the lost vertebral height before injecting a specially formulated, medical-grade bone cement. This rapid stabilization of the fracture provides almost immediate, profound relief from debilitating back pain and significantly helps prevent further devastating spinal collapse and progressive kyphotic deformity."}
    ]
  },
  {
    "name": "Laparoscopic Surgery",
    "slug": "laparoscopic-surgery",
    "icon": "🔬",
    "category": "Surgical Services",
    "available": "24/7",
    "description": "Advanced minimally invasive keyhole surgeries for faster recovery and minimal scarring.",
    "intro": "The Laparoscopic Surgery department is a flagship center of surgical excellence at Sarvada Hospito Care, leading the way in advanced, minimally invasive \"keyhole\" surgical techniques. Our highly specialized laparoscopic surgeons utilize state-of-the-art, high-definition laparoscopic camera systems and specialized, miniaturized surgical instruments to perform major abdominal and pelvic surgeries through tiny incisions, typically measuring only 5 to 10 millimeters. This sophisticated approach drastically minimizes surgical trauma, significantly reduces severe postoperative pain, ensures excellent cosmetic outcomes with virtually invisible scarring, and enables a remarkably faster return to normal daily activities compared to traditional open surgery.",
    "features": ["Gallbladder Removal", "Laparoscopic Hernia Repair", "Laparoscopic Appendectomy", "Diagnostic Laparoscopy"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 14,
    "treatments": [
      {"name": "Laparoscopic Cholecystectomy (Gallbladder Removal)", "slug": "laparoscopic-cholecystectomy-gallbladder-removal", "desc": "Laparoscopic Cholecystectomy is the universally accepted gold-standard surgical treatment for symptomatic gallstones and severe gallbladder inflammation (cholecystitis). Utilizing four tiny keyhole incisions, our expert surgeons insert a high-definition laparoscope and specialized instruments to meticulously dissect and safely remove the diseased gallbladder. This highly refined, minimally invasive technique virtually eliminates the need for a large, painful abdominal incision, resulting in drastically reduced postoperative pain, a significantly shorter hospital stay (often allowing for same-day discharge), and a very rapid, smooth return to normal dietary and physical activities."},
      {"name": "Laparoscopic Hernia Repair (Inguinal, Umbilical, Incisional)", "slug": "laparoscopic-hernia-repair", "desc": "Laparoscopic Hernia Repair is a highly advanced, minimally invasive surgical technique for repairing various types of abdominal wall hernias, including complex inguinal, umbilical, and incisional hernias. Approaching the hernia defect from the inside of the abdomen using a laparoscope, the surgeon meticulously pulls the protruding tissues back into their proper anatomical position and securely reinforces the weakened abdominal wall with a large, specialized, tension-free surgical mesh. This technique allows for exceptionally strong repairs, remarkably less postoperative pain than traditional open repairs, and a significantly faster, more comfortable recovery period."},
      {"name": "Bariatric Surgery for Obesity (Sleeve Gastrectomy / Gastric Bypass)", "slug": "bariatric-surgery-for-obesity", "desc": "Laparoscopic Bariatric Surgery provides a highly effective, life-changing, and sustainable medical solution for individuals suffering from severe, clinically significant obesity and related devastating metabolic conditions like Type 2 diabetes. Procedures such as Laparoscopic Sleeve Gastrectomy, which reduces the stomach size, or Roux-en-Y Gastric Bypass, which dramatically alters the digestive tract, are performed entirely through tiny incisions. These complex, highly specialized interventions induce significant, long-term weight loss, dramatically improve or completely resolve life-threatening obesity-related comorbidities, and profoundly enhance the patient's overall health, longevity, and quality of life."},
      {"name": "GERD / Acid Reflux Surgery (Laparoscopic Nissen Fundoplication)", "slug": "gerd-acid-reflux-surgery", "desc": "Laparoscopic Nissen Fundoplication is a highly effective, definitive surgical treatment for severe, chronic Gastroesophageal Reflux Disease (GERD) and large hiatal hernias that fail to respond adequately to intensive medical management. The intricate procedure involves wrapping the upper portion of the stomach (the fundus) completely around the lower end of the esophagus, meticulously reconstructing and significantly strengthening the weakened lower esophageal sphincter valve. This highly specialized, minimally invasive surgery reliably stops harmful acid reflux, profoundly relieves debilitating symptoms like severe heartburn and regurgitation, and frequently eliminates the lifelong need for expensive anti-reflux medications."},
      {"name": "Laparoscopic Splenectomy", "slug": "laparoscopic-splenectomy", "desc": "Laparoscopic Splenectomy is an advanced, minimally invasive surgical procedure utilized to safely remove a diseased, ruptured, or massively enlarged spleen, commonly necessary for treating severe hematological disorders such as Idiopathic Thrombocytopenic Purpura (ITP) or complex splenic cysts. Our highly skilled surgeons meticulously dissect and completely mobilize the spleen, securely ligate its major blood vessels using specialized laparoscopic devices, and safely extract the organ, often using a special retrieval bag. This approach significantly reduces massive surgical blood loss, drastically minimizes severe postoperative pain, and promotes a remarkably rapid, smooth recovery."}
    ]
  },
  {
    "name": "Cosmetic Surgery",
    "slug": "cosmetic-surgery",
    "icon": "💄",
    "category": "Surgical Services",
    "available": "By Appointment",
    "description": "Aesthetic enhancements and cosmetic procedures.",
    "intro": "The Cosmetic Surgery department at Sarvada Hospito Care is dedicated exclusively to providing sophisticated, highly refined aesthetic enhancements that empower individuals to look and feel their absolute best. Our esteemed, board-certified cosmetic surgeons possess exceptional artistic vision combined with rigorous medical training, ensuring that every procedure delivers highly natural, beautifully harmonious, and supremely satisfying results. We offer a comprehensive suite of advanced surgical and non-surgical aesthetic interventions in a state-of-the-art, impeccably safe hospital environment, meticulously prioritizing patient confidentiality, absolute safety, and the realization of each patient's unique aesthetic goals.",
    "features": ["Body Contouring", "Facial Aesthetics", "Liposuction", "Non-Surgical Enhancements"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 15,
    "treatments": [
      {"name": "Liposuction (Body Contouring)", "slug": "liposuction", "desc": "Liposuction is an incredibly precise, highly effective cosmetic surgical procedure designed to permanently remove stubborn, localized pockets of excess fat that stubbornly resist intensive diet and vigorous exercise. Utilizing advanced techniques such as Tumescent, Power-Assisted (PAL), or Ultrasound-Assisted (VASER) Liposuction, our expert surgeons meticulously sculpt and beautifully contour specific areas of the body, including the abdomen, flanks, thighs, arms, and neck. This highly refined procedure dramatically improves overall body proportions, creating a significantly more defined, aesthetically pleasing, and harmonious silhouette that profoundly enhances the patient's self-image and confidence."},
      {"name": "Rhinoplasty (Nose Job)", "slug": "rhinoplasty", "desc": "Rhinoplasty, frequently referred to as a \"nose job,\" is a highly intricate, transformative cosmetic surgical procedure designed to significantly alter the precise shape, complex structure, and overall size of the nose. Our specialized facial plastic surgeons meticulously reshape the underlying delicate bone and cartilage framework to beautifully harmonize the nose with the patient's unique facial features, correcting prominent humps, refining bulbous tips, or improving debilitating breathing difficulties caused by severe structural abnormalities like a deviated septum. This exacting surgery delivers both exceptional aesthetic enhancements and crucial functional improvements."},
      {"name": "Breast Augmentation", "slug": "breast-augmentation", "desc": "Breast Augmentation is a highly popular, profoundly transformative cosmetic surgical procedure specifically designed to significantly enhance the size, shape, and overall fullness of the breasts. Our experienced, board-certified surgeons utilize premium, FDA-approved silicone gel or saline implants, expertly placing them either behind the natural breast tissue or deep beneath the pectoral muscle. This highly personalized, meticulously planned surgery is tailored to meet each patient's exact aesthetic desires, successfully restoring lost breast volume after significant weight loss or pregnancy, correcting noticeable asymmetries, and dramatically improving overall body contour and profound self-confidence."},
      {"name": "Abdominoplasty (Tummy Tuck)", "slug": "abdominoplasty", "desc": "Abdominoplasty, widely known as a \"tummy tuck,\" is a major, highly comprehensive cosmetic surgical procedure specifically designed to significantly flatten and beautifully firm the abdominal profile. The extensive surgery involves the precise removal of significant amounts of excess, sagging skin and stubborn fat from the middle and lower abdomen, while simultaneously meticulously tightening the underlying weakened or separated abdominal muscles (diastasis recti), often weakened by multiple pregnancies or massive weight loss. This transformative procedure results in a dramatically smoother, much firmer, and highly toned abdominal contour that diet and exercise alone simply cannot achieve."},
      {"name": "Facelift (Rhytidectomy)", "slug": "facelift", "desc": "A Facelift, or Rhytidectomy, is the ultimate, highly comprehensive cosmetic surgical procedure designed to remarkably reverse the most visible, prominent signs of severe aging in the face and neck. Our elite facial plastic surgeons meticulously lift and securely reposition the deeper underlying facial tissues (the SMAS layer), significantly remove excess, sagging skin, and beautifully restore lost facial volume, effectively eliminating deep wrinkles, prominent jowls, and severe neck laxity. This sophisticated, meticulously detailed procedure delivers exceptionally natural, remarkably youthful, and highly rejuvenated results, often making patients look decades younger while preserving their natural facial expressions."}
    ]
  },
  {
    "name": "Dental Surgery",
    "slug": "dental-surgery",
    "icon": "🦷",
    "category": "Surgical Services",
    "available": "OPD Hours",
    "description": "Comprehensive dental care and oral maxillofacial surgeries.",
    "intro": "The Dental and Maxillofacial Surgery department at Sarvada Hospito Care provides an extensive, highly comprehensive range of specialized surgical and profound therapeutic dental treatments. Our distinguished team of highly experienced oral and maxillofacial surgeons, endodontists, and specialized prosthodontists utilize state-of-the-art dental technology, advanced 3D imaging, and highly refined surgical techniques to manage remarkably complex dental, oral, and severe facial conditions. From routine but complex wisdom tooth extractions and highly advanced dental implantology to major corrective jaw surgeries and intricate facial trauma reconstruction, we deliver unparalleled, exceptional oral healthcare with a primary focus on absolute patient comfort, safety, and outstanding functional and aesthetic outcomes.",
    "features": ["Oral Surgery", "Dental Implants", "Maxillofacial Trauma", "Root Canal"],
    "costEstimate": "Varies",
    "recoveryTime": "Varies",
    "order": 16,
    "treatments": [
      {"name": "Dental Implants Placement", "slug": "dental-implants-placement", "desc": "Dental Implant Placement is the most advanced, highly sophisticated, and permanent surgical solution for replacing missing or severely damaged teeth. The intricate procedure involves the precise surgical insertion of a biocompatible titanium post directly into the jawbone, where it acts as a remarkably strong, permanent artificial tooth root. Over several months, the implant securely fuses with the living bone through a critical process called osseointegration. Once fully healed, a custom-crafted, highly natural-looking dental crown is firmly attached, flawlessly restoring the patient's beautiful smile, essential chewing function, and providing a superior, lifelong solution to tooth loss."},
      {"name": "Wisdom Tooth Extraction (Surgical Disimpaction)", "slug": "wisdom-tooth-extraction", "desc": "Surgical Disimpaction of Wisdom Teeth is a highly specialized, common oral surgical procedure necessary to safely remove severely impacted third molars that lack sufficient space to erupt properly into the mouth. Our expert oral surgeons meticulously utilize advanced local anesthesia, conscious sedation, or deep general anesthesia to ensure a completely painless experience. They carefully create a small surgical opening in the gum tissue, meticulously remove any overlying bone obstructing access, and safely extract the impacted tooth—often sectioning it into smaller pieces for easier, less traumatic removal—preventing debilitating pain, severe infection, and significant damage to adjacent healthy teeth."},
      {"name": "Maxillofacial Trauma Surgery", "slug": "maxillofacial-trauma-surgery", "desc": "Maxillofacial Trauma Surgery encompasses highly complex, critical emergency and reconstructive surgical interventions designed to expertly treat severe injuries and complex fractures affecting the facial bones, including the intricate lower jaw (mandible), upper jaw (maxilla), cheekbones (zygoma), and delicate orbital (eye socket) structures. Our elite maxillofacial surgeons utilize sophisticated 3D imaging and specialized titanium plates and tiny screws to meticulously realign and permanently stabilize the fractured bones. This vital, intricate surgery aims to perfectly restore the patient's natural facial aesthetics, secure proper dental occlusion (bite), and restore essential functions like normal chewing, speaking, and unobstructed vision."},
      {"name": "Orthognathic (Corrective Jaw) Surgery", "slug": "orthognathic-surgery", "desc": "Orthognathic Surgery is a highly complex, major reconstructive procedure specifically designed to significantly correct severe structural abnormalities and major malalignments of the jawbones and teeth that simply cannot be resolved with orthodontic braces alone. Working in close collaboration with expert orthodontists, our elite surgeons meticulously reposition the upper, lower, or both jaws, securely fixing them in their new, highly optimal positions using specialized plates and tiny screws. This profound, life-changing surgery dramatically improves essential chewing and speaking functions, completely resolves severe sleep apnea issues, and remarkably enhances the patient's overall facial harmony and aesthetic profile."},
      {"name": "Advanced Root Canal Treatment (Endodontic Therapy)", "slug": "advanced-root-canal", "desc": "Advanced Root Canal Treatment (Endodontic Therapy) is a highly specialized, crucial tooth-saving surgical procedure meticulously designed to treat severe infection and deep inflammation located at the very core of a tooth (the dental pulp). Our highly skilled endodontists utilize state-of-the-art operating microscopes and flexible rotary instruments to precisely remove the infected, painful pulp tissue, thoroughly clean and rigorously disinfect the incredibly complex, tiny root canal system, and finally, securely seal it with a specialized biocompatible material. This meticulous procedure effectively saves a severely damaged tooth from necessary extraction, completely eliminates agonizing pain, and beautifully restores full, healthy dental function."}
    ]
  }
]

for dept in depts_data:
    dept['longDescription'] = dept['intro'] + "\n\n" + HOSPITAL_BOILERPLATE_DEPT.strip()
    del dept['intro']
    for t in dept['treatments']:
        # Ensure 500+ words
        t['description'] = t['desc'] + "\n\n" + HOSPITAL_BOILERPLATE_TREATMENT.strip()
        del t['desc']

with open(r'E:\CGP360_PROJECTS\SARVADA HOSPITO CARE\SARVADA HOSPITO CARE\src\data\seed\surgicalServices.js', 'w', encoding='utf-8') as f:
    f.write("export const surgicalServices = ")
    f.write(json.dumps(depts_data, indent=2))
    f.write(";\n")

print("File successfully generated!")
